# Generated by Django 2.0.5 on 2018-07-15 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20180715_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 8, 21, 641800)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 8, 21, 641800)),
        ),
    ]
