# Generated by Django 2.0.5 on 2018-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20180715_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
