# Generated by Django 2.0.5 on 2018-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20180715_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
